# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1

- powershell: |
    $slackWebhookUrl = "https://hooks.slack.com/services/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"
    $body = @{
        text = "Azure DevOps pipeline succeeded!"
    } | ConvertTo-Json

    Invoke-RestMethod -Uri $slackWebhookUrl -Method Post -Body $body -ContentType 'application/json'
  displayName: 'Send Slack Notification'
  condition: succeeded()  # Run the PowerShell script only when the previous steps succeed
